// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/ks-home/CharcoalMinimal.tsx": () => import("../components/mockups/ks-home/CharcoalMinimal.tsx"),
  "./components/mockups/ks-home/CleanBlue.tsx": () => import("../components/mockups/ks-home/CleanBlue.tsx"),
  "./components/mockups/ks-home/SlatePro.tsx": () => import("../components/mockups/ks-home/SlatePro.tsx")
};
